[theme]
# Cor de destaque para itens selecionados (pills, tags multiselect, botões primários)
primaryColor = "#aab2b9ff"

# Fundo principal da aplicação
backgroundColor = "#c9d2dbff"

# Fundo secundário (usado em inputs, textareas, pills não selecionadas)
secondaryBackgroundColor = "#D7D8D9"

# Cor do texto principal
textColor = "#011A33"
